FROM demoregistry.dataman-inc.com/shurenyun/centos7-nginx-1.8.0:omega.v0.2.4

ADD ./frontend.tar.gz  /usr/local/share/

RUN rm -rf /usr/share/nginx/html/* && \
    cp -r /usr/local/share/frontend/glance/build /usr/share/nginx/html/dashboard.shurenyun.com && \
    rm -rf /usr/local/share/frontend*

RUN rm -rf /etc/nginx/certs

COPY update.sh /

COPY entrypoint.sh /

WORKDIR /

ENTRYPOINT ["./entrypoint.sh"]